<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the `roles` table and seeds the 8 default roles with immutable
 * default permissions.
 *
 * Default roles (cannot be deleted):
 *   System, Admin, Site Manager, Manager, Editor, Author, Member, Non-Member
 *
 * Backward-compatible aliases (ROLE_USER, ROLE_SUPER_ADMIN) are also seeded
 * as non-deletable roles with is_hidden=true so they don't clutter the admin UI
 * but remain available for legacy permission checks.
 *
 * Each role's default_permissions are immutable — they cannot be modified by
 * anyone. Only custom_permissions can be added/removed through the admin API.
 */
final class Version20260919140000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create roles table and seed 8 default roles with immutable default permissions.';
	}

	public function up(Schema $schema): void
	{
		$table = $this->qualifiedTable();

		$this->addSql(sprintf('CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, value VARCHAR(128) NOT NULL, is_default BOOLEAN NOT NULL DEFAULT true, is_deletable BOOLEAN NOT NULL DEFAULT false, is_hidden BOOLEAN NOT NULL DEFAULT false, default_permissions JSON NOT NULL DEFAULT \'{\'::json, custom_permissions JSON NOT NULL DEFAULT \'{\'::json, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))', $table));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_role_value ON %s (value)', $table));
		$this->addSql(sprintf('CREATE INDEX idx_role_hidden ON %s (is_hidden)', $table));

		$now = date('Y-m-d H:i:s');

		$roles = [
			[
				'name' => 'System',
				'value' => 'ROLE_SYSTEM',
				'is_hidden' => false,
				'default_permissions' => '{"*": ["*"]}',
			],
			[
				'name' => 'Admin',
				'value' => 'ROLE_ADMIN',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'application' => ['read', 'write', 'delete'],
					'site' => ['read', 'write', 'delete', 'configure'],
					'site_group' => ['read', 'write', 'delete'],
					'user' => ['read', 'write', 'delete'],
					'user_group' => ['read', 'write', 'delete'],
					'role' => ['read', 'write'],
					'page' => ['read', 'write', 'delete', 'publish'],
					'lexeme' => ['read', 'write', 'delete'],
					'plugin' => ['read', 'write', 'install', 'remove', 'enable', 'disable'],
					'search' => ['read', 'write', 'rebuild', 'configure'],
					'audit_log' => ['read'],
				]),
			],
			[
				'name' => 'Site Manager',
				'value' => 'ROLE_SITE_MANAGER',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'site' => ['read', 'write'],
					'application' => ['read'],
					'user' => ['read'],
					'page' => ['read', 'write', 'publish'],
					'plugin' => ['read'],
					'search' => ['read', 'rebuild'],
					'audit_log' => ['read'],
				]),
			],
			[
				'name' => 'Manager',
				'value' => 'ROLE_MANAGER',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'page' => ['read', 'write', 'publish'],
					'user' => ['read'],
					'application' => ['read'],
					'site' => ['read'],
					'search' => ['read'],
					'audit_log' => ['read'],
				]),
			],
			[
				'name' => 'Editor',
				'value' => 'ROLE_EDITOR',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'page' => ['read', 'write', 'publish'],
					'search' => ['read'],
				]),
			],
			[
				'name' => 'Author',
				'value' => 'ROLE_AUTHOR',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'page' => ['read', 'write'],
				]),
			],
			[
				'name' => 'Member',
				'value' => 'ROLE_MEMBER',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'profile' => ['read', 'write'],
				]),
			],
			[
				'name' => 'Non-Member',
				'value' => 'ROLE_NON_MEMBER',
				'is_hidden' => false,
				'default_permissions' => $this->permissionsJson([
					'search' => ['read'],
				]),
			],
			// Backward-compatible aliases (hidden from admin UI, no Role entity
			// needed — they exist in UserRoleEnum and are resolved via role_hierarchy)
		];

		foreach ($roles as $role) {
			$this->addSql(
				sprintf('INSERT INTO %s (name, value, is_default, is_deletable, is_hidden, default_permissions, custom_permissions, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', $table),
				[
					$role['name'],
					$role['value'],
					'true',   // All seeded roles are system-defined (is_default = true)
					'false',  // System roles cannot be deleted
					$role['is_hidden'] ? 'true' : 'false',
					$role['default_permissions'],
					'{}',
					$now,
					$now,
				],
			);
		}
	}

	public function down(Schema $schema): void
	{
		$table = $this->qualifiedTable();

		$this->addSql(sprintf('DROP TABLE %s', $table));
	}

	private function qualifiedTable(): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		if (!is_string($schema) || '' === $schema) {
			return 'roles';
		}

		return $schema.'.roles';
	}

	private function permissionsJson(array $permissions): string
	{
		return json_encode($permissions, JSON_UNESCAPED_SLASHES);
	}
}
