<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the api_tokens table for the ApiToken entity used by the admin SPA
 * to make authenticated API calls.
 *
 * The table is created in the schema configured by DB_SCHEMA (applied to
 * application entities by the SchemaListener), defaulting to "public".
 */
final class Version20260920074000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create the api_tokens table.';
	}

	public function up(Schema $schema): void
	{
		$table = $this->qualifiedTable();
		$prefix = $this->schemaPrefix();
		$objectsTable = is_string($prefix) && '' !== $prefix ? $prefix.'.objects' : 'objects';

		// DbObject declares an @Id on its `id` column; the objects table
		// created outside of migrations is missing this primary key. Add it
		// before the FK on api_tokens.user_id references objects(id).
		$this->addSql(sprintf('ALTER TABLE %s ADD PRIMARY KEY (id)', $objectsTable));

		$this->addSql(sprintf('CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id BIGINT NOT NULL, PRIMARY KEY(id))', $table));
		$this->addSql(sprintf('CREATE UNIQUE INDEX UNIQ_650FD5E55F37A13B ON %s (token)', $table));
		$this->addSql(sprintf('CREATE INDEX IDX_650FD5E5A76ED395 ON %s (user_id)', $table));
		$this->addSql(sprintf('ALTER TABLE %s ADD CONSTRAINT FK_650FD5E5A76ED395 FOREIGN KEY (user_id) REFERENCES %s (id) NOT DEFERRABLE', $table, $objectsTable));
	}

	public function down(Schema $schema): void
	{
		$table = $this->qualifiedTable();
		$prefix = $this->schemaPrefix();
		$objectsTable = is_string($prefix) && '' !== $prefix ? $prefix.'.objects' : 'objects';

		$this->addSql(sprintf('DROP TABLE %s', $table));
		$this->addSql(sprintf('ALTER TABLE %s DROP CONSTRAINT objects_pkey', $objectsTable));
	}

	private function qualifiedTable(): string
	{
		$prefix = $this->schemaPrefix();

		return is_string($prefix) && '' !== $prefix ? $prefix.'.api_tokens' : 'api_tokens';
	}

	private function schemaPrefix(): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		return is_string($schema) ? $schema : '';
	}
}
