<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the audit_log_entries table for the AuditLogEntry entity, used by
 * the audit logging system to record all entity inserts, updates, and deletes.
 *
 * The table is created in the schema configured by DB_SCHEMA (applied to
 * application entities by the SchemaListener), defaulting to "public".
 */
final class Version20260920075000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create the audit_log_entries table for audit logging.';
	}

	public function up(Schema $schema): void
	{
		$table = $this->qualifiedTable();
		$prefix = $this->schemaPrefix();
		$objectsTable = is_string($prefix) && '' !== $prefix ? $prefix.'.objects' : 'objects';

		$this->addSql(sprintf('CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, actor_type VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, object_type VARCHAR(128) NOT NULL, object_id BIGINT DEFAULT NULL, before_state JSON DEFAULT NULL, after_state JSON DEFAULT NULL, context JSON DEFAULT \'{\'::json NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, request_uri TEXT DEFAULT NULL, PRIMARY KEY(id))', $table));
		$this->addSql(sprintf('CREATE INDEX idx_audit_object ON %s (object_type, object_id)', $table));
		$this->addSql(sprintf('CREATE INDEX idx_audit_user ON %s (user_id)', $table));
		$this->addSql(sprintf('CREATE INDEX idx_audit_created ON %s (created_at)', $table));
		$this->addSql(sprintf('ALTER TABLE %s ADD CONSTRAINT FK_4D32F51DA76ED395 FOREIGN KEY (user_id) REFERENCES %s (id) NOT DEFERRABLE', $table, $objectsTable));
	}

	public function down(Schema $schema): void
	{
		$table = $this->qualifiedTable();

		$this->addSql(sprintf('DROP TABLE %s', $table));
	}

	private function qualifiedTable(): string
	{
		$prefix = $this->schemaPrefix();

		return is_string($prefix) && '' !== $prefix ? $prefix.'.audit_log_entries' : 'audit_log_entries';
	}

	private function schemaPrefix(): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		return is_string($schema) ? $schema : '';
	}
}
