<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the full-text search configuration tables.
 *
 * Tables store search index configurations, fields, analyzer layers, filters,
 * configuration groups, and site groups. All tables are qualified with the
 * DB_SCHEMA configured for application entities (see DoctrineSchemaSubscriber),
 * defaulting to the search path when DB_SCHEMA is unset.
 */
final class Version20260919120000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create full-text search configuration tables.';
	}

	public function up(Schema $schema): void
	{
		$prefix = $this->qualifiedPrefix();

		$this->addSql(sprintf('CREATE TABLE %ssearch_indexes (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(128) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(16) NOT NULL DEFAULT \'custom\', engine VARCHAR(64) NOT NULL DEFAULT \'postgresql\', language VARCHAR(32) NOT NULL DEFAULT \'english\', description TEXT DEFAULT NULL, system_locked BOOLEAN NOT NULL DEFAULT false, is_enabled BOOLEAN NOT NULL DEFAULT true, site_id BIGINT DEFAULT NULL, config_group_id BIGINT DEFAULT NULL, options JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_search_index_slug ON %ssearch_indexes (slug)', $prefix));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_search_index_slug_site ON %ssearch_indexes (slug, site_id)', $prefix));

		$this->addSql(sprintf('CREATE TABLE %ssearch_index_fields (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, search_index_id BIGINT NOT NULL, name VARCHAR(128) NOT NULL, source_type VARCHAR(16) NOT NULL DEFAULT \'property\', source TEXT NOT NULL, data_type VARCHAR(32) NOT NULL DEFAULT \'text\', weight SMALLINT NOT NULL DEFAULT 1, language VARCHAR(32) DEFAULT NULL, analyzer_name VARCHAR(128) DEFAULT NULL, is_facetable BOOLEAN NOT NULL DEFAULT false, is_sortable BOOLEAN NOT NULL DEFAULT false, position INT NOT NULL DEFAULT 0, PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE INDEX idx_field_index_pos ON %ssearch_index_fields (search_index_id, position)', $prefix));

		$this->addSql(sprintf('CREATE TABLE %ssearch_analyzer_layers (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, search_index_id BIGINT DEFAULT NULL, field_id BIGINT DEFAULT NULL, type VARCHAR(32) NOT NULL DEFAULT \'tokenfilter\', position INT NOT NULL DEFAULT 0, options JSON NOT NULL, PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE INDEX idx_layer_analyzer_pos ON %ssearch_analyzer_layers (name, position)', $prefix));

		$this->addSql(sprintf('CREATE TABLE %ssearch_filters (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, search_index_id BIGINT NOT NULL, name VARCHAR(128) NOT NULL, label VARCHAR(255) NOT NULL, mode VARCHAR(32) NOT NULL DEFAULT \'query_time\', visibility VARCHAR(16) NOT NULL DEFAULT \'public_frontend\', required_roles JSON DEFAULT NULL, hook VARCHAR(255) DEFAULT NULL, options JSON NOT NULL, is_enabled BOOLEAN NOT NULL DEFAULT true, PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE INDEX idx_filter_index ON %ssearch_filters (search_index_id)', $prefix));

		$this->addSql(sprintf('CREATE TABLE %ssearch_config_groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_system BOOLEAN NOT NULL DEFAULT false, site_id BIGINT DEFAULT NULL, search_index_ids JSON NOT NULL DEFAULT \'[]\', site_assignments JSON NOT NULL DEFAULT \'[]\', site_group_assignments JSON NOT NULL DEFAULT \'[]\', PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_config_group_name ON %ssearch_config_groups (name)', $prefix));

		$this->addSql(sprintf('CREATE TABLE %ssearch_site_groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_system BOOLEAN NOT NULL DEFAULT false, site_ids JSON NOT NULL DEFAULT \'[]\', PRIMARY KEY(id))', $prefix));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_site_group_name ON %ssearch_site_groups (name)', $prefix));

		$this->addSql(sprintf('ALTER TABLE %ssearch_index_fields ADD CONSTRAINT fk_search_index_fields_search_index FOREIGN KEY (search_index_id) REFERENCES %ssearch_indexes (id) NOT DEFERRABLE INITIALLY IMMEDIATE', $prefix, $prefix));
		$this->addSql(sprintf('ALTER TABLE %ssearch_analyzer_layers ADD CONSTRAINT fk_search_analyzer_layers_search_index FOREIGN KEY (search_index_id) REFERENCES %ssearch_indexes (id) NOT DEFERRABLE INITIALLY IMMEDIATE', $prefix, $prefix));
		$this->addSql(sprintf('ALTER TABLE %ssearch_analyzer_layers ADD CONSTRAINT fk_search_analyzer_layers_field FOREIGN KEY (field_id) REFERENCES %ssearch_index_fields (id) NOT DEFERRABLE INITIALLY IMMEDIATE', $prefix, $prefix));
		$this->addSql(sprintf('ALTER TABLE %ssearch_filters ADD CONSTRAINT fk_search_filters_search_index FOREIGN KEY (search_index_id) REFERENCES %ssearch_indexes (id) NOT DEFERRABLE INITIALLY IMMEDIATE', $prefix, $prefix));
	}

	public function down(Schema $schema): void
	{
		$prefix = $this->qualifiedPrefix();

		$this->addSql(sprintf('DROP TABLE %ssearch_filters', $prefix));
		$this->addSql(sprintf('DROP TABLE %ssearch_analyzer_layers', $prefix));
		$this->addSql(sprintf('DROP TABLE %ssearch_index_fields', $prefix));
		$this->addSql(sprintf('DROP TABLE %ssearch_config_groups', $prefix));
		$this->addSql(sprintf('DROP TABLE %ssearch_site_groups', $prefix));
		$this->addSql(sprintf('DROP TABLE %ssearch_indexes', $prefix));
	}

	private function qualifiedPrefix(): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		return is_string($schema) && '' !== $schema ? $schema.'.' : '';
	}
}
