<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds admin-managed icon sets (`icon_sets`) and their sanitised SVG icons (`icons`).
 *
 * Icons are stored only after {@see \iikiti\CMS\Web\Icon\SvgSanitizer} accepts them.
 * Deleting a set cascades to its icons.
 */
final class Version20261010120000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add icon_sets and icons tables for admin-managed icon sets.';
	}

	public function up(Schema $schema): void
	{
		$sets = $this->table('icon_sets');
		$icons = $this->table('icons');

		$this->addSql(sprintf(
			'CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))',
			$sets
		));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_icon_set_slug ON %s (slug)', $sets));

		$this->addSql(sprintf(
			'CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, svg TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, icon_set_id BIGINT NOT NULL, PRIMARY KEY (id))',
			$icons
		));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_icon_set_name ON %s (icon_set_id, name)', $icons));
		$this->addSql(sprintf('CREATE INDEX IDX_527490B948D16F3B ON %s (icon_set_id)', $icons));
		$this->addSql(sprintf(
			'ALTER TABLE %s ADD CONSTRAINT FK_527490B948D16F3B FOREIGN KEY (icon_set_id) REFERENCES %s (id) ON DELETE CASCADE NOT DEFERRABLE',
			$icons,
			$sets
		));
	}

	public function down(Schema $schema): void
	{
		$this->addSql(sprintf('DROP TABLE %s', $this->table('icons')));
		$this->addSql(sprintf('DROP TABLE %s', $this->table('icon_sets')));
	}

	private function table(string $name): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		return is_string($schema) && '' !== $schema ? $schema.'.'.$name : $name;
	}
}
