<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create the plugin_registry table used to audit installed plugins.
 *
 * The table is created in the schema configured by DB_SCHEMA (applied to
 * application entities by the SchemaListener), defaulting to "public".
 */
final class Version20260913170000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Create the plugin_registry table.';
	}

	public function up(Schema $schema): void
	{
		$table = $this->qualifiedTable();

		$this->addSql(sprintf('CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(128) NOT NULL, site_id VARCHAR(64) DEFAULT NULL, version VARCHAR(32) NOT NULL, source VARCHAR(32) NOT NULL, state VARCHAR(32) NOT NULL, installed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))', $table));
		$this->addSql(sprintf('CREATE UNIQUE INDEX uniq_plugin_site ON %s (slug, site_id)', $table));
	}

	public function down(Schema $schema): void
	{
		$this->addSql(sprintf('DROP TABLE %s', $this->qualifiedTable()));
	}

	private function qualifiedTable(): string
	{
		$schema = $_ENV['DB_SCHEMA'] ?? $_SERVER['DB_SCHEMA'] ?? getenv('DB_SCHEMA');

		if (!is_string($schema) || '' === $schema) {
			return 'plugin_registry';
		}

		return $schema.'.plugin_registry';
	}
}
