doctrine:
    orm:
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: cache.database

framework:
    cache:
        pools:
            doctrine.system_cache_pool:
                adapter: cache.system
