# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    iikiti\CMS\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Filters/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Manually configure the SchemaListener to bind the schema parameter.
    # The #[AsDoctrineListener] attribute handles the auto-configuration (tagging).
    # We only need to define the service here to bind the constructor argument.
    iikiti\CMS\Doctrine\SchemaListener:
        bind:
            $schema: '%env(DB_SCHEMA)%'
